# Generated by Django 3.0.4 on 2021-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
