# Generated by Django 3.0.4 on 2021-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
