# Generated by Django 3.0.4 on 2021-03-10 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 13, 20, 25, 150802, tzinfo=utc)),
        ),
    ]
